name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Получение кода из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Установка Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 3. Установка зависимостей
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        python -m pip install --upgrade pip
        pip install --user buildozer cython==0.29.19

    # 4. Установка Android SDK
    - name: Setup Android SDK
      uses: actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.0
        ndk: 23b

    # 5. Принятие лицензий Android SDK
    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    # 6. Инициализация Buildozer
    - name: Initialize Buildozer
      run: |
        buildozer init
        sed -i 's/title = My Application/title = Notepad/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = notepad/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = org.my/' buildozer.spec
        sed -i 's/#icon.filename = %(source.dir)s\/icon.png/icon.filename = icon.png/' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy==2.2.0,sqlite3/' buildozer.spec
        sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/' buildozer.spec
        sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,db/' buildozer.spec
        sed -i 's/#source.include_patterns = assets\/*,README.md/source.include_patterns = icon.png/' buildozer.spec
        sed -i 's/#android.api = 27/android.api = 33/' buildozer.spec
        sed -i 's/#android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/#android.ndk = 23b/android.ndk = 23b/' buildozer.spec

    # 7. Диагностика перед сборкой
    - name: Debug info
      run: |
        ls -la
        python --version
        pip list | grep -E 'buildozer|cython|kivy'
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "PATH: $PATH"
        buildozer --version

    # 8. Компиляция APK
    - name: Build APK
      run: |
        buildozer android debug
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}

    # 9. Загрузка APK как артефакта
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: notepad-apk
        path: bin/*.apk
