name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Получение кода из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Очистка места на диске
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        df -h

    # 3. Установка Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 4. Установка зависимостей
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
        python -m pip install --upgrade pip
        pip install --user buildozer cython==0.29.19

    # 5. Установка Android SDK и NDK вручную
    - name: Install Android SDK and NDK
      run: |
        mkdir -p android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        ANDROID_HOME=$(pwd)/android-sdk
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH:$(pwd)/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV
        echo "PATH=$PATH:$(pwd)/android-sdk/platform-tools" >> $GITHUB_ENV
        echo "Set ANDROID_HOME to: $ANDROID_HOME"

    # 6. Проверка доступных пакетов
    - name: List available SDK packages
      run: |
        echo "Current ANDROID_HOME: $ANDROID_HOME"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep ndk

    # 7. Установка SDK и NDK
    - name: Verify sdkmanager
      run: |
        echo "Current ANDROID_HOME: $ANDROID_HOME"
        ls -la $ANDROID_HOME
        ls -la $ANDROID_HOME/cmdline-tools/latest/bin
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --version
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;33.0.0" "platforms;android-33" "ndk;25.2.9519653"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses

    # 8. Инициализация Buildozer
    - name: Initialize Buildozer
      run: |
        echo "ANDROID_HOME in Buildozer step: $ANDROID_HOME"
        buildozer init
        sed -i 's/title = My Application/title = Notepad/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = notepad/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = org.my/' buildozer.spec
        sed -i 's/#icon.filename = %(source.dir)s\/icon.png/icon.filename = icon.png/' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy==2.2.0,sqlite3/' buildozer.spec
        sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/' buildozer.spec
        sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,db/' buildozer.spec
        sed -i 's/#source.include_patterns = assets\/*,README.md/source.include_patterns = icon.png/' buildozer.spec
        sed -i 's/#android.api = 27/android.api = 33/' buildozer.spec
        sed -i 's/#android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/#android.ndk = 23b/android.ndk = 25.2.9519653/' buildozer.spec

    # 9. Диагностика перед сборкой
    - name: Debug info
      run: |
        lsb_release -a
        ls -la
        python --version
        pip list | grep -E 'buildozer|cython|kivy'
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "PATH: $PATH"
        buildozer --version
        ls -la $ANDROID_HOME
        ls -la $ANDROID_HOME/cmdline-tools/latest/bin

    # 10. Компиляция APK
    - name: Build APK
      run: |
        echo "ANDROID_HOME in Build APK step: $ANDROID_HOME"
        buildozer android debug
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}

    # 11. Загрузка APK как артефакта
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: notepad-apk
        path: bin/*.apk
