name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Используем более старую версию Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          df -h

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # Более стабильная версия для buildozer

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          python -m pip install --upgrade pip
          pip install --user buildozer==1.4.0 cython==0.29.36

      - name: Setup Android SDK using action
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          build-tools: 30.0.3
          ndk: 23.1.7779620

      - name: Move SDK to buildozer location
        run: |
          mkdir -p ~/.buildozer/android/platform
          cp -r $ANDROID_HOME ~/.buildozer/android/platform/android-sdk
          
          # Создание совместимости со старой структурой
          cd ~/.buildozer/android/platform/android-sdk
          mkdir -p tools/bin
          if [ -d "cmdline-tools/latest/bin" ]; then
            ln -sf $(pwd)/cmdline-tools/latest/bin/sdkmanager tools/bin/sdkmanager
            ln -sf $(pwd)/cmdline-tools/latest/bin/avdmanager tools/bin/avdmanager
          fi

      - name: Configure Buildozer
        run: |
          buildozer init
          
          # Простая конфигурация
          sed -i 's/title = My Application/title = Notepad/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = notepad/' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.my/' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy==2.1.0/' buildozer.spec
          sed -i 's/#android.api = 27/android.api = 30/' buildozer.spec
          sed -i 's/#android.minapi = 21/android.minapi = 21/' buildozer.spec
          sed -i 's/#android.ndk = 25.2.9519653/android.ndk = 23.1.7779620/' buildozer.spec
          sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec

      - name: Build APK
        timeout-minutes: 90
        run: |
          export ANDROID_HOME=~/.buildozer/android/platform/android-sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          buildozer android debug
        env:
          ANDROID_HOME: ~/.buildozer/android/platform/android-sdk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: notepad-apk
          path: bin/*.apk
