name: Build APK

on:
  push:
    branches: [ main ]  # Запуск при пуше в ветку main
  workflow_dispatch:    # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Получение кода из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Установка зависимостей
    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev gettext
        pip install --user --upgrade buildozer cython==0.29.19

    # 3. Инициализация Buildozer
    - name: Initialize Buildozer
      run: |
        buildozer init
        sed -i 's/title = My Application/title = Notepad/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = notepad/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = org.my/' buildozer.spec
        sed -i 's/#icon.filename = %(source.dir)s\/icon.png/icon.filename = icon.png/' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy==2.2.0,sqlite3/' buildozer.spec
        sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/' buildozer.spec
        sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,db/' buildozer.spec
        sed -i 's/#source.include_patterns = assets\/*,README.md/source.include_patterns = notepad.db,icon.png/' buildozer.spec

    # 4. Компиляция APK
    - name: Build APK
      run: |
        buildozer android debug

    # 5. Загрузка APK как артефакта
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: notepad-apk
        path: bin/*.apk
